name: Pull Docker

on:
  workflow_dispatch:

jobs:
  Pull:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
        
      - name: Pull Image from GitHub Container Registry
        run: |
          docker pull ghcr.io/jposselt/test-container:latest
          
      - name: List Images
        run: |
          docker image list
      
      - name: Run Image
        run: |
          docker run test-container
